nft-landscape-1/PITCHME.md
I added info regarding the EOSIO NFT proposal which is currently being worked on.
=> Added some info regarding the EOSIO NFT proposal

README.md
and make the contribution process compatible for external contributors.
=> Soften language for requirements

src/cryptography/bulletproofs-protocols/MainReport.md
Changes:
- Revised heading names to make the report more intuitive
- Added section **How the Proof System for Protocol 1 Works, Shrinking by Recursion**
- Updated section **Inner-Product Verification through Multi-Exponentiation (Protocol 2)**
=> Bulletproof protocols update

src/cryptography/digital_signatures/introduction_schnorr_signatures.md
Update Schnorr talk with:
* Comment about broken 2-round MuSig
* Replay attack section
=> Add replay attacks section to Schnorr/Musig

src/cryptography/digital_signatures/introduction_schnorr_signatures.md
Hi Cayle, please could you have a look and let me know if you are happy with this report.
@CjS77 
@hansieodendaal
=> Final changes committed and pushed.

src/cryptography/digital_signatures/introduction_schnorr_signatures.md
=> Fixed challenge to not use public nonce for case without nonce

src/SUMMARY.md, src/labs/notes.md, src/theme/css/general.css
Adds colourful note box functionality to TLU
=> Add notes and warning boxes

src/SUMMARY.md, src/digital-assets/nft-landscape-1/sources/PITCHME.link.md
... that were not working in hosted TLU
=> fix-tlu-links

src/digital-assets/nft-landscape-1/sources/PITCHME.link.md
=> fix-tlu-link2

src/SUMMARY.md, src/protocols/dht/MainReport.md
@sdbondi 
Hi Stan, final changes for your comments.
=> Final checks for DHT report.

src/protocols/grin-beam-comparison/MainReport.md
Hi @philipr-za, I've formatted Section 6.4 in accordance with the TLU Style Guide, checked the links, formatted the references and restricted the line lengths to the required 120 characters per line to facilitate checking of the changes.
Please let me know if you're happy with these formatting changes before I proceed with the editing (grammar, spelling, consistency, flow, etc.).
Thanks and regards
Denise
=> Formatted Section 6.4 (Grin beam comparison) for review

src/protocols/grin-design-choice-criticisms/MainReport.md
Hi @neonknight64, I've completed the formatting of Section 6.5 in accordance with the TLU Style Guide. Before I continue with the next stage (technical editing), please could you let me know if you're happy with the formatting.
Thanks and regards
Denise
=> Formatted Section 6.5 (Grin Design Choice Criticisms...) for review

src/protocols/atomic-swaps/AtomicSwaps.md
Hi @SWvheerden , I've completed the formatting checks on this section, so that it is in accordance with the TLU Style Guide. This also included checking the links and limiting the line lengths to 120 characters, to improve legibility.
Please let me know if you're happy with the formatting changes. I will then edit the section (for grammar, spelling, flow, consistency, logic, etc.).
Thanks and regards, Denise.
=> New PR for formatted Section 6.6 (Atomic Swaps) for review

src/cryptography/bulletproofs-and-mimblewimble/MainReport.md
=> Section consistency check

src/cryptography/digital_signatures/introduction_schnorr_signatures.md
=> Section 1.2 Consistency Check.

src/cryptography/scriptless-scripts/introduction-to-scriptless-scripts.md
=> Section 1.3 consistency check

src/cryptography/bulletproofs-protocols/MainReport.md
=> Section 1.8 Consistency Check

src/cryptography/musig-schnorr-sig-scheme/The_MuSig_Schnorr_Signature_Scheme.md
=> Section 1.4 Consistency Check

src/cryptography/fraud-proofs-1/MainReport.md
* Consistency edit. Spacing, references, links.
* Adjusted bullet spacing in appendix
=> Section 1.5 Consistency Check (Recreation of PR #173.)

src/protocols/mimblewimble-mp-bp-utxo/MainReport.md
Added simple polynomial illustration, clarified Pedersen VSS test of shards.
=> Mimblewimble Multipary UTXO Fixes

src/consensus-mechanisms/BFT-consensus-mechanisms-applications/MainReport.md, src/digital-assets/confidential-assets/MainReport.md, src/digital-assets/howey-application-to-blockchain/MainReport.md, src/layer2scaling/layer2scaling-landscape/layer2scaling-survey.md, src/layer2scaling/more-landscape/landscape-update.md, src/merged-mining/merged-mining-scene/MergedMiningIntroduction.md, src/protocols/atomic-swaps/AtomicSwaps.md, src/protocols/dht/MainReport.md, src/protocols/grin-beam-comparison/MainReport.md, src/protocols/grin-design-choice-criticisms/MainReport.md, src/protocols/grin-protocol-overview/MainReport.md, src/protocols/mimblewimble-1/MainReport.md
Hi @hansieodendaal , please could you review my minor edits to Sections 2.2, 3.1, 3.2, 4.1, 5.1, 6.2, 6.4 and 6.5.
In Cayle's chapter, Section 6.2, there is some inconsistency in the table headings: some are centered and some are left justified. I am not sure how to fix this.
Please let me have your comments, when you get a chance.
Thanks and regards
Denise
=> Step 2 in consistency edit - minor edits.

src/layer2scaling/directed-acyclic-graphs/DAGs.md
Hi @hansieodendaal, if you get a chance, please review my changes. I have two questions:
1. The meaning of "start watching at 30min" is unclear to me.
2. I would like to left-justify 'Summary' in all sections, in accordance with the other level 3 headings. This does not seem to render correctly. It looks correct in the md file, but not when rendered. Please let me know how to fix this. 
Thanks very much.
=> Edited DAGs videos

src/consensus-mechanisms/BFT/understanding_bft_consensus.md
Hi @Kevoulee, please review my technical edits and let me know what you think.
=> BFT videos curation - Technical editing changes.

src/protocols/tor-or-not-too-tor/tor-or-not-too-tor.md
Hi @leet4tari, I've reviewed your Tor section and have suggested a small change to the note about Tor vs services. Please let me know what you think.
=> Final review of Tor section

src/consensus-mechanisms/BFT/understanding_bft_consensus.md
Hi @Kevoulee, please review my edits and let me know what you think. Your summaries sound good.
=> Edited summaries

src/protocols/intro-to-i2P/MainReport.md
Hi @mhlangagc, please review my final edits. As well as language edits, I've fixed the references so that the inline references are live in the rendered text, when you hover your cursor over them. Please let me know if you'd like any changes. I created a new branch for these changes, as I see you worked on my previous branch. I hope that's okay.
=> Intro to i2p network final edit

src/cryptography/bulletproofs-protocols/MainReport.md
=> fix_mcp_bulletproof_reference

src/protocols/grin-beam-comparison/MainReport.md
Several comments and updates to Beam description in the document
=> Updated Beam description

src/protocols/grin-beam-comparison/MainReport.md
Final technical editing review.
=> Section 6.4 Grin vs. BEAM

README.md
Hi @hansieodendaal, this is the updated branch with changes to future topics. I will soon close the other PR (ks-future-topics-update) and refer to this PR (ks-future-topics). Many thanks.
=> update future topic list

src/network-analysis/probabilistic-attack/MainReport.md
Hi @Kevoulee, I've completed the first part of the technical editing process, i.e. formatting. Please could you review my formatting changes and let me know if you are happy, or if you'd like any changes. I'll then do the language editing.
Two questions, please:
1. Under 'Law of large numbers', the second paragraph is incomplete. How should the sentence end?
2. Reference [[9]] in the text is not 'live'. I've fixed other references, but cannot establish the problem with this one. Can you please help?
Please let me know when I can proceed with the language editing. Thanks.
=> Probabilistic Attack Vector Analysis Building Blocks - formatting

src/scaling/laser-beam/MainReport.md
Hi @hansieodendaal, please review my changes and let me have your comments. I have the following questions, please:
1. Under notation used, is the info in the last bullet point correct? (, e.g. .... does this indicate an example?) 
2. The following reference links are not available: [6], [8] and [9].
Thanks and regards
Denise
=> Laser Beam - Technical editing

src/protocols/mimblewimble-mp-bp-utxo/MainReport.md
Conclusions about using the Bulletproofs MPC protocol vs. Grin method updated
=> update on conclusions for Bulletproofs MPC protocol

src/scaling/laser-beam/MainReport.md
Hi @hansieodendaal, please see my latest changes.
=> Laser Beam - Final edit

src/cryptography/bulletproofs-and-mimblewimble/MainReport.md, src/cryptography/bulletproofs-protocols/MainReport.md, src/digital-assets/confidential-assets/MainReport.md, src/protocols/mimblewimble-mp-bp-utxo/MainReport.md, src/scaling/laser-beam/MainReport.md
Fixes to how equation numbers are rendered
=> eqn_number_rendering

book.toml
- Google Analytics flag activated
- Code changed to proper Google Analytics code
=> google-analytics-trackiing

src/cryptography/r1cs-bulletproofs/mainreport.md
Hi @hansieodendaal and @Empiech007
This looks good. I only have one question, please. In Table 3, No. 6, it is unclear what creates its own transcript.
All the links work, as well as the contents.
Please let me have your comments.
Thanks and regards.
=> R1cs bulletproofs final edits da

src/theme/css/general.css
Fixed legibility of note, note info and warning boxes.
=> note-note_info-warning-boxes

src/cryptography/r1cs-bulletproofs/mainreport.md
=> r1cs-bulletproofs-edits

README.md, src/preface/introduction.md
- Added GitHub links for submitting issues and pull requests
- Updated _Future Topics_ in GitHub
=> github_links

src/cryptography/amortization-bp-ipp/mainreport.md
Hi @Empiech007, please see my suggested changes to Appendix B. I see a few problems with some of the equations, e.g. Corollary 2 - the font of the text parts ('for all') is a serif font and not a sans serif font, as used for text elsewhere.
Also, there are some strange characters in the Lemma 2 equations.
=> New branch created for suggested editing changes to Appendix B.

_posts/tari/2021-09-13-TariScript_for_dummies.md
=> fix some typos

_posts/cryptography/2020-02-01-cryptography.md, _posts/network-analysis/2020-08-01-network-analysis.md
Fixed permalinks on main Cryptography and Network Analysis pages
=> Permalink fixes

_posts/course1-blockchain/2021-01-04-module4.md
Looks good. Minor cosmetic changes.
=> chore: review course 1

_posts/course2-money/2021-02-01-course2.md, _posts/course2-money/2021-02-01-module1.md, _posts/course2-money/2021-02-03-module3.md
=> chore: review course 2

_includes/content/cryptography/02-introduction-schnorr-signatures.md, _posts/course3-crypto101/2021-03-01-course3.md
=> chore: review course 3

_includes/content/digital-assets/02-nft-survey.md, _posts/course4-digital-assets/2021-04-01-course4.md, _posts/course4-digital-assets/2021-04-01-digital-assets.md, _posts/course4-digital-assets/2021-04-02-application-of-howey-network-token-sales.md, _posts/course4-digital-assets/2021-04-03-nft-survey.md, _posts/course4-digital-assets/2021-04-04-confidential-assets.md, _posts/course4-digital-assets/2021-04-05-Lelantus.md
Checked course 4 contents, added some context and added an into video to Lelantus.
=> feat: review course 4

_includes/content/consensus-mechanisms/03-Introduction-to-Applications-of-Byzantine-Consensus-Mechanisms.md, _includes/content/cryptography/03-introduction-to-scriptless-scripts.md, _includes/content/cryptography/06-bulletproofs-and-mimblewimble.md, _includes/content/mining/01-merged-mining.md, _includes/content/mining/02-MergedMiningIntroduction.md, _includes/content/protocols/04-grin-vs-beam-comparison.md, _includes/content/scaling/01-layer2scaling-survey.md, _includes/content/scaling/04-laser-beam.md, _includes/content/tari/01-TariScript_for_dummies.md
Removed / replaced broken links in articles
=> fix: broken links
